name: Terraform Deployment

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-2
  AWS_ACCOUNT_ID: 445567099272

jobs:
  epam-web-app-deployment:
    name: Terraform Init & Apply
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: arn:aws:iam::445567099272:role/github-oidc-role
          aws-region: ap-southeast-2
          role-session-name: GitHubActions

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        
